.TH "srcs/container.c" 3 "Mon Nov 6 2017" "Version 1.0.0" "pamela" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/container.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pamela\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBchange_container_mdp\fP (const char *user, const char *old_mdp, const char *new_mdp)"
.br
.ti -1c
.RI "int \fBclose_container\fP (const char *user)"
.br
.ti -1c
.RI "int \fBopen_container\fP (const char *user, const char *pass)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int change_container_mdp (const char * user, const char * old_mdp, const char * new_mdp)"
Change key of container 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIold_mdp\fP 
.br
\fInew_mdp\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 60 of file container\&.c\&.
.SS "int close_container (const char * user)"

.PP
Definition at line 67 of file container\&.c\&.
.SS "int open_container (const char * user, const char * pass)"
Open container (open secure + mount + setup access) 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP 
.br
\fIpass\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 82 of file container\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for pamela from the source code\&.
