.TH "srcs/utils.c" 3 "Mon Nov 6 2017" "Version 1.0.0" "pamela" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/utils.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pamela\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBget_user_home\fP (const char *user)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* get_user_home (const char * user)"
Get home for dir to username 
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP username 
.RE
.PP
\fBReturns:\fP
.RS 4
char *home_dir (home dir path) / NULL (if not found) 
.RE
.PP

.PP
Definition at line 18 of file utils\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for pamela from the source code\&.
